
# train
dataset:
  clean_dir: 'F:/datasets/div_flick'


#test
num_workers: 2
batch_size: 16

num_epochs: 3000

learning_rate_SRN: 0.0001
step_size: 600
gamma_SRN: 0.5

pretrain: False
DA_TRAIN_epoch: -1
DA_learning_rate: 0.0002
DA_step_size: 60
gamma_DA: 0.5




saving: True
save_path: da_model
save_model_interval: 50


patch_size: 64
scale: 4


Degradation_Predictor:
  in_nc: 3
  nf: 64
  num_params: 64
  use_bias: True

Reblur_Branch:
  img_channel: 3
  output_img_channel: 3
  nc: 64
  nz: 64
  scale: 4




DASR:
  scale: 4
  rgb_range: 1.0





# degradation
blur_kernel: 21
blur_type: iso_gaussian #(iso_gaussian | aniso_gaussian)
sig_min: 0.2
sig_max: 4.0
lambda_min: 0.2
lambda_max: 4.0
noise: 0.0


use_focal_weight: False


